variables:
  DOCKER_IMAGE: mcr.microsoft.com/dotnet/sdk:8.0
include:
  - component: $CI_SERVER_FQDN/websn/ci-templates/dotnet-build@v0.0.13
    inputs:
      stage: build
      docker-image: $DOCKER_IMAGE
  - component: $CI_SERVER_FQDN/websn/ci-templates/dotnet-deploy@v0.0.13
    inputs:
      stage: build
      docker-image: $DOCKER_IMAGE

stages:
- build
- deploy
